apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: chess-game-deployment
spec:
  selector:
    matchLabels:
      app: chess-game
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: chess-game
    spec:
      containers:
        - name: chess-game
          image: vakabinto/chess-game:v1 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: chess-game-svc
spec:
  selector:
    app: chess-game
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.
